workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/


version: 2
jobs:
  build:
    docker:
      - image: cibuilds/chrome-extension:latest
    steps:
      - checkout
      - run:
          name: "Install Dependencies Part 1"
          command: |
            apk update
            apk add nodejs
      - run:
          name: "Hacky fix for NPM: https://stackoverflow.com/a/52196681"
          command: |
            npm config set unsafe-perm true
      - run:
          name: "Install Dependencies Part 2"
          command: |
            npm install -g browserify
            npm install -g web-ext
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: browserify
          command: browserify background.js > background_browserify.js
      - run:
          name: "Create js/secret.js"
          command: |
            echo "const CLIENT_ID_DEV = '$SNOOWRAP_CLIENT_ID_DEV';" >> js/secret.js
            echo "const CLIENT_ID_PROD = '$SNOOWRAP_CLIENT_ID_PROD';" >> js/secret.js
      - run:
          name: "Run Tests"
          command: npm run test
      - run:
          name: "Package Extension"
          command: |
            web-ext build
      - store_artifacts:
          path: web-ext-artifacts/
